version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-odkfi1pgbvrq"
s3_prefix = "sam-app"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = ["TensorFlowInferenceFunction=137929100830.dkr.ecr.us-east-1.amazonaws.com/samapp7427b055/tensorflowinferencefunction402a36b7repo"]
